### ISSUE TITLE
Länkar till gamla Storm är fel på varianter

### ISSUE THREAD

**Issue by GustavSilberfeldt** [StormCommerce/storm-admin-angular#3]
EX https://stormstage.enferno.se/stormProducts/Variant.aspx?prd=28302719

Dvs det saknas en "/" mellan storm och Products.

Det verkar uppstå när man klickar sig till gamla storm och sedan går bakåt tillbaka till nya Admin. Då försvinner en "/" i länkarna.

**Comment by tomasisby** [comment]
Default länk saknade slut /
